-- INSERT INTO blacklist_person_attribute (attribute_name, description) VALUES
-- ('nationality', 'Nationality of the person'),
-- ('siara_number', 'Folio SIARA'),
-- ('agreement_number', 'Folio acuerdo'),
-- ('agreement_date', 'Fecha del acuerdo'),
-- ('comments', 'Additional comments'),
-- ('delete_reason', 'Reason for deletion'),
-- ('official_deletion_date', 'Official date of deletion');
-- INSERT INTO person_attribute (attribute_name, description) VALUES
-- ('PEP Type', 'Type of Politically Exposed Person (none, national, foreign)'),
-- ('Nationality', 'Person''s nationality'),
